### ISSUE TITLE
Add seasonal day/night variation

### ISSUE THREAD

**Issue by sofar** [MinetestForFun/time_regulation#2]
With a bit of math, one could easily vary the day/night length according to a sine curve and create the effect of seasons, at least daylight wise.

It would require 2 parameters: `length` and `offset` (read like "year length" and "latitude")

the daily variation can be calculated by

```
    ratio = ((math.cos((day_of_year / length) * 2 * math.pi()) * offset) / 2.0) + 0.5
    nightratio = ratio
    dayratio = - ratio 
```

`offset` should be a number between 0.0 and 1.0. At 0.0, there is no seasonal variation. At 1.0, the longest day has no darkness, and the shortest day has no lightness. Reasonable values are likely between 0.0 and 0.5 or so. At 0.5, the longest day is 75% of day length. At 0.2, the longest day is 60% of day length.

I'd cap ratio at 0.9 or so, at 0.8 the longest day would be 90% daytime, and the moon would have to scream across the sky 5x as fast as normal.

**Comment by Lymkwi** [comment]
I have one question though, length should be expressed in seconds, minutes, hours, days or years? This formula fails everytime I use it no matter what offset I use, with similar values (99.x & 0.x), so I assume I have the length wrong.

**Comment by sofar** [comment]
minetest days, but you need to actually have a consistent day counter, because time can be skipped and may reset on server restart.

**Comment by Lymkwi** [comment]
I think it is fairly easy to retrieve and compute the value of "game_time", since it's affected by time changes. However, maintaining a strict and independant day counter, with all the cases possible (settime, time_regulation in idle mode, etc) it would be inacurate.
I'll figure out a way to do that.

**Comment by sofar** [comment]
Is it? I had thought it was purely "world has been running for X seconds", and did not account for `/time` changes.

**Comment by Lymkwi** [comment]
Well, I assumed it was, but after some tests it seems untouched by time changes..
I'll have to think of something else.

**Comment by sofar** [comment]
We'll have to overwrite `core.set_timeofday`. I had previously written a concept 'calendar' mod that has some of this code, I can see if I can brush it up again.

**Comment by Lymkwi** [comment]
Well, I assumed it was, but after some tests it seems untouched by time changes..
I'll have to think of something else.

**Comment by sofar** [comment]
https://github.com/minetest/minetest/pull/3820

this will solve all our problems - it provides a consistent monotonic day counter. We can use this directly to calculate day/night ratio, all you have to do is define the length of a year in days.

**Comment by Lymkwi** [comment]
Great. I haven't touched the code since the last time we exchanged on this issue, so I haven't made any progress. I'm going to make other attempts at calculating the lengths myself and the ratios depending on the day of the year.

**Comment by Fixer-007** [comment]
3820 was merged, now is your turn :}

**Comment by Lymkwi** [comment]
I had worked my way around the issue by using real life values (`os.date("%j")` and `os.date("%Y")`) but the formula kept giving me ludicrously low values for right ratio. I've twisted it a little bit and it seem to work.
I figured that keeping the season calculation based on real life time would be less confusing to the players, and also that it would be easier to compute, so I'll push that.

**Comment by sofar** [comment]
I don't get it.

Minetest time already is different from real-time. If someone skips 100 days(by typing `/time 0` 100x) to get to summer from winter, your code will keep them in winter until 4 months of actual real time passes? Did I see that right?

**Comment by Lymkwi** [comment]
> Minetest time already is different from real-time. If someone skips 100 days(by typing /time 0 100x) to get to summer from winter, your code will keep them in winter until 4 months of actual real time passes? Did I see that right?

Since I based my calculations on real life date then you will only enter winter period in the game when it is winter in real life, 6 real time months after summer, even if you skip hundreds of days in the game, it doesn't matter. I've also planned on adding a second option that would let you use the game's date to calculate seasonal ratio, as I think it was requested first.

**Comment by sofar** [comment]
> Since I based my calculations on real life date then you will only enter winter period in the game when it is winter in real life, 6 real time months after summer, even if you skip hundreds of days in the game, it doesn't matter.

I would never use it if that's what this mod did. I'm really waiting for:

> I've also planned on adding a second option that would let you use the game's date to calculate seasonal ratio, as I think it was requested first.

Yes please!

**Comment by Fixer-007** [comment]
Agree with sofar.

**Comment by Lymkwi** [comment]
There, https://github.com/minetest-mods/time_regulation/commit/da8bbfee9abf7b6e8f197f4ade7127e6dc805647 .
I also reworked the status system and the order in which I run my functions after the server boots (and I fixed a few calculation mistakes).
